#!/bin/sh

SRC_DIRS="scribble original"
INPUTS="input_1.fasta input_2.fasta input_3.fasta input_4.fasta"
REPETITIONS=1
MAX_NCPU=16

for SRC_DIR in $SRC_DIRS; do
    echo > ./$SRC_DIR.time
    cd $SRC_DIR
    go build
    cd ..
done

for SRC_DIR in $SRC_DIRS; do
    for INPUT in $INPUTS; do
        for NCPU in $(seq 1 ${MAX_NCPU}); do
            for ITER in $(seq 1 ${REPETITIONS}); do
                echo "($ITER of ${REPETITIONS}) ./$SRC_DIR/$SRC_DIR -ncpu $NCPU < ./input/$INPUT >> ./$SRC_DIR.time"
                ./$SRC_DIR/$SRC_DIR -ncpu $NCPU < ./input/$INPUT >> ./$SRC_DIR.time
                tail -1 ./$SRC_DIR.time
            done
        done
    done
done
