#!/bin/bash

SRC_DIRS="scribble original"
INPUTS="2000 3000 5500 11000"
MAX_NCPU=12
REPEAT=${REPEAT:=20}

for SRC_DIR in $SRC_DIRS; do
    echo > ./$SRC_DIR.time
    cd $SRC_DIR
    go build
    cd ..
done

for SRC_DIR in $SRC_DIRS; do
    for INPUT in $INPUTS; do
        for NCPU in $(seq 1 ${MAX_NCPU}); do
            for ITER in $(seq 1 ${REPEAT}); do
                echo "($ITER of ${REPEAT}) ./$SRC_DIR/$SRC_DIR -ncpu $NCPU -n $INPUT >> ./$SRC_DIR.time"
                ./$SRC_DIR/$SRC_DIR -ncpu $NCPU -n $INPUT >> ./$SRC_DIR.time
            done
        done
    done
done
